<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="filetree" nsURI="http://filetree/1.0" nsPrefix="filetree">
  <eClassifiers xsi:type="ecore:EClass" name="FileTree" eSuperTypes="#//Container"/>
  <eClassifiers xsi:type="ecore:EClass" name="FileTreeElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="#//Path"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Container"
        eOpposite="#//Container/children"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Directory" eSuperTypes="#//Container"/>
  <eClassifiers xsi:type="ecore:EClass" name="File" eSuperTypes="#//FileTreeElement"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Path" instanceClassName="java.nio.file.Path"/>
  <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="#//FileTreeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//FileTreeElement" containment="true" eOpposite="#//FileTreeElement/parent"/>
  </eClassifiers>
</ecore:EPackage>
