<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uimodel" nsURI="http://uimodel/1.0" nsPrefix="uimodel">
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkTree" eType="ecore:EClass FileTree.ecore#//Tree"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="localTree" eType="ecore:EClass FileTree.ecore#//Tree"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rootDir" eType="ecore:EDataType FileTree.ecore#//Path"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UiModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" eType="#//Network"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network"/>
</ecore:EPackage>
